### ISSUE TITLE
UX/UI enhancement: Ability to remove speaker

### ISSUE THREAD

**Issue by chrisaldrich** [kevinmarks/noterlive#10]
<a href="https://github.com/kevinmarks/noterlive/issues" class="u-in-reply-to"></a>UX/UI enhancement: Ability to remove speaker

During the heat of live-tweeting, one can accidentally have typos, input wrong speaker information, or need to add additional speaker information. It could be helpful to have a "Remove Speaker button" next to "Save Speaker" to delete an incorrectly input version.

**Comment by kevinmarks** [comment]
Makes sense - added a delete button next to 'save speaker'
