### ISSUE TITLE
Can't delete Speakers without Twitter Handles

### ISSUE THREAD

**Issue by chrisaldrich** [kevinmarks/noterlive#11]
If an added speaker doesn't have a Twitter handle, the delete button doesn't work to delete them.

**Comment by kevinmarks** [comment]
Put the text of their name in as the twitter handle, as that is what is sent to twitter. I could default it to anon I suppose, but if you do leave it blank, yes, it will not be removable.

**Comment by kevinmarks** [comment]
wondering if I should disallow blank ones

**Comment by chrisaldrich** [comment]
<a href="https://github.com/kevinmarks/noterlive/issues/11#issuecomment-242472007" class="u-in-reply-to"></a>I can't see a reason it wouldn't be a good idea to do so. Perhaps if it's not a valid Twitter name, it gets wrapped in slighly different code and/or CSS, to indicate it won't resolve to an actual link?

Example: http://boffosocko.com/2016/10/15/notes-from-day-2-of-dodging-the-memory-hole-saving-online-news-friday-october-14-2016/#Peter Arnett:

**Comment by kevinmarks** [comment]
fixed
