### ISSUE TITLE
Display issue for Speakers without Twitter Handles

### ISSUE THREAD

**Issue by chrisaldrich** [kevinmarks/noterlive#12]
The display of speakers without Twitter handles could default to their names and/or URLs instead of being left blank.

![noterlive](https://cloud.githubusercontent.com/assets/5882943/17978623/cecc11aa-6aab-11e6-91d1-4ed92b3d89c7.PNG)

**Comment by kevinmarks** [comment]
if they have no twitter handle, you can put a short plaintext of their name in the @ field, as that is what is sent to twitter. I should make this clearer. This also helps abbreviate names to surnames when quoting a lot in tweets. see http://www.kevinmarks.com/nexteconomy2015-11-12.html where soem speakers didn't have handles or urls I could find, so used names like this:

https://twitter.com/kevinmarks/statuses/664925484673867776

**Comment by kevinmarks** [comment]
fixed
